README.md
I tried the example and got class not found, I think they need the namespace?
=> Added namespace for phone number format examples in readme

src/libphonenumber/PhoneNumberUtil.php
This moves the job of decoding the hex strings from the VM to the parser, resulting in less overhead at runtime during the initialization of `PhoneNumberUtil`.
=> Faster initialization of $numericCharacters

src/libphonenumber/PhoneNumber.php
This ensures consistency on types throughout the project, as suggested in #72.
=> Typecast values in PhoneNumber setters

.travis.yml, Tests/libphonenumber/Tests/Issues/PHP7Test.php, build.xml, build/data-patches/001-PHP7-PL.patch, src/libphonenumber/data/PhoneNumberMetadata_PL.php
Add phing command to patch the source data, this changes the regex for Poland
which allows the PHP7 tests to pass
Works around #79 and [PHP Bug #70304](https://bugs.php.net/bug.php?id=70304)
Thanks to [/u/OzzyGiritli](https://www.reddit.com/user/OzzyGiritli) for
the idea to split the Regex.
=> Patch Polish data to fix PHP7 compatibility

src/libphonenumber/PhoneNumberUtil.php
A recent requirement was to reject numbers containing alphanumeric characters. currently `+49 123 456-xxxx` gets parsed successfully, leading to a `PhoneNumber` instance containing `nationalNumber = 1234569999` which is not what we expected.
I didn't check all the existing rules & behavior of the underlying google library, but we wanted an Exception in this case. Trying to extend `PhoneNumberUtil` was a bit more complicated since `PhoneNumberUtil::getInstance` explicitly does `new PhoneNumberUtil` which means we had to copy the whole method just to ensure we got our own instance back.
changing `new PhoneNumberUtil` to `new static` would allow such an extension w/o any further code, w/o breaking compatibility.
@giggsey i had three, imo unrelated, test failures caused by 'Cocos [Keeling] …
=> allow extended PhoneNumberUtil instance

src/libphonenumber/PhoneNumberUtil.php
The method always returns an array, please keep the SCA's happy :)
=> PhoneNumberUtil::getRegionCodesForCountryCode fix return type hint

composer.json
I think "/src/geocoding/data/" can be excluded from autoload since it doesn't contains any thing needs to be autoloaded. 
Another reason is I'm sort of implementing my own autoloading mechanism with parsing. And the files under "/src/geocoding/data/" take very long time to parse.
=> Exclude "/src/geocoding/data/" from autoload

src/PhoneNumberToTimeZonesMapper.php, tests/Issues/Issue159Test.php
I didn't see the extra `!` in the original Java code and that seems to break the logic anyway.
=> Remove extra !

src/PhoneNumberUtil.php, tests/core/PhoneNumberUtilTest.php
Because a lot of duplications in code of `null` value provided in parser I've thought about making it default. 
```php
$phoneUtil = \libphonenumber\PhoneNumberUtil::getInstance();
$phone = $phoneUtil->parse($number, null);
```
It will work by this way:
```php
$phoneUtil = \libphonenumber\PhoneNumberUtil::getInstance();
$phone = $phoneUtil->parse($number);
```
=> Default null for for parser default region

src/PhoneNumber.php, tests/core/PhoneNumberTest.php
I was using `assertEquals` in some tests that was not passing because of the nested phone number which has not the same state after unserialization.
=> Fixed PhoneNumber::unserialize

docs/PhoneNumberOfflineGeocoder.md, docs/PhoneNumberToCarrierMapper.md
The extension hasn't been required for a while now, the docs should match this.
=> Remove incorrect intl requirement from docs

docs/PhoneNumberOfflineGeocoder.md
=> Wrong word for United States In Korean

src/PhoneNumberUtil.php, tests/Issues/Issue360Test.php
PHP doesn't allow method overloading, so we have to merge `isPossibleNumber(PhoneNumber $number)` and `isPossibleNumber(string $number, string $region)`.
We were incorrectly checking if the second parameter was not null, when we only needed to check if the first param was a PhoneNumber or a string.
Fixes #360
=> Fix bug when calling isPossibleNumber with string, null

README.md
Due to the lack of maintenance of the original bundle,
we forked it and maintain it. It already has 17K downloads
as we speak and should be the recommended one.
=> Update PhoneNumberBundle to a maintained project

src/PhoneNumberUtil.php
If the region code or country calling code are invalid, the getMetadata* methods will return null
=> PhoneNumberUtil::getMetadata* methods can return null

METADATA-VERSION.txt, src/carrier/data/en/224.php, src/carrier/data/en/230.php, src/carrier/data/en/254.php, src/carrier/data/en/65.php, src/data/PhoneNumberMetadata_GN.php, src/data/PhoneNumberMetadata_KE.php, src/data/PhoneNumberMetadata_MU.php, src/data/PhoneNumberMetadata_SG.php
- Updated phone metadata for region code(s): GN, KE, MU, SG
- Updated carrier data for country calling code(s):
65 (en), 224 (en), 230 (en), 254 (en)
=> Upstream metadata changes from Google for v8.12.15

src/PhoneNumberUtil.php
The google/libphonenumber javascript version has been updated such that it can both take lowercase/uppercase strings and also ensure that numeric regionCodes are not counted as valid.
See https://github.com/google/libphonenumber/blob/master/javascript/i18n/phonenumbers/phonenumberutil.js#L1658
See #480 for more info.
=> Update `PhoneNumberUtil::isValidRegionCode()` to work the same as javascript version

src/ShortNumberInfo.php, tests/core/ShortNumberInfoTest.php
With a valid, regular land-line number given to `ShortNumberInfo::isValidShortNumber(PhoneNumber)`, a deprecation notice is issued for the null parameter value to `strtoupper` when it reaches `regionDialingFromMatchesNumber`.
=> Prevent null from reaching `strtoupper` in `ShortNumberInfo`

tests/Issues/LocaleTest.php
Avoid CLDR differences in the tests.
=> Remove Turkey from tests due to name change

src/PhoneNumber.php
This PR addresses #567.
The `equals` method of the `PhoneNumber` class does different checks on each property which can be simplified with a simple `===` comparison. Additionally we can work on the properties directly without using haser and getter methods. Both of these changes improve performance a lot.
A short circuit for comparison of the identical instance was added.
The comparison of the class name was removed, too, because the type check of the parameters already makes sure that an instance of PhoneNumber is passed.
If somebody extends the class he can override and  extend the equals method, too. So a class name check is not required.
=> Simplified PhoneNumber instance comparison and improved performance

src/PhoneNumberUtil.php
extractPossibleNumber in PhoneNumberUtil.php wants a string for the $number parameter as also stated in the method's documention (since a string with special charactars like '-' cannot be an integer), but was type hinted as an integer causing PHP stan errors.
=> Fix string parameter type hinted as integer

composer.json
`libphonenumber-for-php-lite` is currently configured to conflict with `libphonenumber-for-php`. This leads to both packages not being able to be installed simultaneously, which is of course intended behavior.
However, this breaks the dependency chain for packages requiring either of them.
Imagine the following scenario:
- project dependencies
- libphonenumber-for-php
- some-package
- some-package dependencies
- libphonenumber-for-php-lite
This will **fail** because of the conflict configuration.
It'd be better to:
1. Configure `libphonenumber-for-php` to replace `libphonenumber-for-php-lite`
2. Remove the conflict configuration from `libphonenumber-for-php-lite`
`replace` means: this package provides everything the other package has as well in the very same namespace (and probably more). …
=> Configure libphonenumber-for-php-lite to be replaced by this package

src/PhoneNumber.php
=> add array type hint to `PhoneNumber::__unserialize`

build/BuildMetadataFromXml.php, src/PhoneNumberMatcher.php, src/PhoneNumberUtil.php
=> PHP 8.4 compatibility

src/PhoneNumberUtil.php, tests/Issues/CodeCoverageTest.php
We have some tests that check manual PhoneNumber objects
Instead of throwing a TypeError, return the null/false options from the functions
=> Fix internal tests

src/PhoneNumber.php, tests/core/PhoneNumberTest.php
While trying to upgrade the PhoneNumberBundle (see https://github.com/odolbeau/phone-number-bundle/pull/193) my application wasn't able to deserialize an "old" serialized phone number.
I added a BC layer in `PhoneNumber` to allow deserialisation of an "old" `CountryCodeSource` (from int to enum).
=> Add a BC layer in PhoneNumber serialize method

src/NumberFormat.php
Resolves https://github.com/giggsey/libphonenumber-for-php/issues/718
=> Remove `@internal` annotation from `NumberFormat` to allow using it for `PhoneNumberUtil::formatByPattern()`
