src/libphonenumber/PhoneNumber.php, src/libphonenumber/PhoneNumberUtil.php
Removes useless function calls.
=> Minor performance improvements

build/libphonenumber/buildtools/Commands/GeneratePhonePrefixDataCommand.php, build/libphonenumber/buildtools/GeneratePhonePrefixData.php, composer.json, src/libphonenumber/PhoneNumberUtil.php
Minor code cleanups after SensioLabsInsight report
=> Code cleanup

README.md
Module for Kohana Framework.  Examples available.
=> Module for Kohana

Tests/libphonenumber/Tests/Issues/Issue106Test.php, src/libphonenumber/prefixmapper/MappingFileProvider.php
Fix mapping file for zh_Hant base on upstream's MappingFileProvider class
=> Fix mapping file for zh_Hant

src/libphonenumber/PhoneNumber.php
libphonenumber-for-php/src/libphonenumber/PhoneNumber.php Line 554 issue #108
=> Fixing issue with hasCountryCodeSource

src/libphonenumber/Matcher.php, src/libphonenumber/MultiFileMetadataSourceImpl.php, src/libphonenumber/NumberFormat.php, src/libphonenumber/NumberParseException.php, src/libphonenumber/PhoneMetadata.php, src/libphonenumber/PhoneNumber.php, src/libphonenumber/PhoneNumberDesc.php, src/libphonenumber/PhoneNumberToCarrierMapper.php, src/libphonenumber/PhoneNumberToTimeZonesMapper.php, src/libphonenumber/PhoneNumberUtil.php, src/libphonenumber/ShortNumberInfo.php, src/libphonenumber/ShortNumberUtil.php, src/libphonenumber/geocoding/PhoneNumberOfflineGeocoder.php, src/libphonenumber/prefixmapper/MappingFileProvider.php, src/libphonenumber/prefixmapper/PhonePrefixMap.php, src/libphonenumber/prefixmapper/PrefixFileReader.php, src/libphonenumber/prefixmapper/PrefixTimeZonesMap.php
I think that if the classes are not declared as `final`, they must be extensible
=> Refactored some classes for extending in other libraries

src/libphonenumber/prefixmapper/PrefixFileReader.php
Reported as a patch via email by Firman Pribadi
=> Fix PrefixFileReader not correctly checking previously loaded files

Tests/libphonenumber/Tests/Issues/Issue135Test.php, Tests/libphonenumber/Tests/core/PhoneNumberUtilTest.php, src/libphonenumber/PhoneNumberUtil.php, src/libphonenumber/geocoding/PhoneNumberOfflineGeocoder.php
=> Initialise static properties before use

Tests/libphonenumber/Tests/core/PhoneMetadataTest.php, src/libphonenumber/Matcher.php, src/libphonenumber/PhoneMetadata.php, src/libphonenumber/ShortNumberUtil.php
This is used by the build script to write to the PHP files.
Ensure that the toArray and fromArray match data.
=> Test PhoneMetadata->toArray()

src/PhoneNumberUtil.php, tests/Issues/Issue152Test.php
Now matches Google's Java implementation
Fixes #152
=> Fix E164 formatting so it doesn't return extensions

src/AsYouTypeFormatter.php, src/PhoneNumberMatcher.php, src/PhoneNumberUtil.php, tests/core/AsYouTypeFormatterTest.php
=> As you type formatter

src/PhoneNumberUtil.php, tests/Issues/Issue175Test.php
=> Initialise static variables required for isViablePhoneNumber

composer.json
=> Update PEAR's version control git to a tagged release

README.md
Updated readme.md with a quick overview with links to get to the part of the readme file
=> Quick links

.editorconfig
Added a .editorconfig to help make a standard for codes syntax when people make a pull request
http://EditorConfig.org
=> Added a .editorconfig

composer.json
=> Convert satooshi/php-coveralls to php-coveralls/php-coveralls

composer.json
Need use php-coveralls/php-coveralls instead.
=> satooshi/php-coveralls - isn`t supported yet.

src/PhoneNumberUtil.php
See https://github.com/kalessil/phpinspectionsea/blob/master/docs/performance.md#slow-array-function-used-in-loop
=> Replace array_merge inside loop

METADATA-VERSION.txt, src/data/PhoneNumberMetadata_CU.php, src/data/PhoneNumberMetadata_EH.php, src/data/PhoneNumberMetadata_MA.php, src/data/ShortNumberMetadata_CU.php, src/geocoding/data/en/53.php
- Updated phone metadata for region code(s): CU, EH, MA
- Updated short number metadata for region code(s): CU
- Updated geocoding data for country calling code(s): 53 (en)
=> Upstream metadata changes from Google for v8.10.11

build/BuildMetadataFromXml.php, build/BuildMetadataPHPFromXml.php, build/GeneratePhonePrefixData.php, build/GenerateTimeZonesMapData.php, build/MetadataFilter.php, src/AsYouTypeFormatter.php, src/PhoneMetadata.php, src/PhoneNumberMatch.php, src/PhoneNumberMatcher.php, src/PhoneNumberToTimeZonesMapper.php, src/RegexBasedMatcher.php, src/geocoding/PhoneNumberOfflineGeocoder.php, tests/Issues/CodeCoverageTest.php, tests/Issues/Issue106Test.php, tests/Issues/Issue35Test.php, tests/Issues/Issue44Test.php, tests/Issues/LocaleTest.php, tests/bootstrap.php, tests/buildtools/MetadataFilterTest.php, tests/carrier/PhoneNumberToCarrierMapperTest.php, tests/core/MatcherTest.php, tests/core/PhoneNumberMatcherTest.php, tests/core/PhoneNumberUtilTest.php, tests/core/ShortNumberInfoTest.php, tests/geocoding/PhoneNumberOfflineGeocoderTest.php, tests/prefixmapper/PrefixFileReaderTest.php
Reproduce with:
php php-cs-fixer --rules=native_function_invocation fix ./ --allow-risky=yes
(php-cs-fixer from : https://cs.symfony.com/)
Details:
https://veewee.github.io/blog/optimizing-php-performance-by-fq-function-calls/
=> Automated native_function_invocation fixes

.github/workflows/ci.yml, composer.json, src/Matcher.php
=> Require mbstring polyfill instead of extension

.gitattributes, .github/workflows/ci.yml, README.md, composer.json, phpunit, tests/Issues/Issue76Test.php, tests/buildtools/BuildMetadataFromXmlTest.php, tests/core/MultiFileMetadataSourceImplTest.php
Provides better PHPUnit support across the PHP versions we support
=> Switch to Symfony's PHPUnit Bridge

composer.json
We have conflicts with packages requiring console 4
=> upgrade symfony console

src/PhoneNumberMatch.php, src/PhoneNumberMatcher.php, tests/core/PhoneNumberMatchTest.php
=> Fix invalid class name (NullPointerException -> InvalidArgumentException)

src/AsYouTypeFormatter.php, src/MultiFileMetadataSourceImpl.php, src/PhoneNumberUtil.php, src/ShortNumberInfo.php, tests/Issues/RegionCodeCaseInsensitiveTest.php
=> Make $regionCode case-insensitive in more locations

src/PhoneNumber.php
Accidental assignment added in #568
=> Fix PhoneNumber comparison

src/MultiFileMetadataSourceImpl.php, src/PhoneNumberMatcher.php, src/PhoneNumberToCarrierMapper.php, src/PhoneNumberUtil.php, src/ShortNumberInfo.php, src/geocoding/PhoneNumberOfflineGeocoder.php, tests/Issues/UKNumbersTest.php, tests/carrier/PhoneNumberToCarrierMapperTest.php, tests/core/AsYouTypeFormatterTest.php, tests/core/MultiFileMetadataSourceImplTest.php, tests/core/PhoneNumberMatcherTest.php, tests/core/PhoneNumberUtilTest.php, tests/core/ShortNumberInfoTest.php, tests/geocoding/PhoneNumberOfflineGeocoderTest.php, tests/prefixmapper/PrefixFileReaderTest.php
=> Load absolute paths to data directories

README.md
Updated a line in the `README.md` file to make it more readable.
=> Updated a line in README.md file 

src/DefaultMetadataLoader.php, src/MetadataLoaderInterface.php, src/PhoneNumberToTimeZonesMapper.php, src/prefixmapper/PrefixFileReader.php
=> Mark some classes as @internal

src/PhoneNumberDesc.php, src/PhoneNumberUtil.php, src/ShortNumberInfo.php
This will help consumers of the API.
=> Document types in public methods

build/Commands/BuildCommand.php, composer.json, phpunit.xml.dist, src/ShortNumberInfo.php
=> Fix generating classmaps for data

src/AsYouTypeFormatter.php, src/PhoneNumberMatcher.php, src/PhoneNumberUtil.php, src/ShortNumberInfo.php
=> Switch static properties to consts

.github/workflows/ci.yml, src/PhoneNumberUtil.php
Use string manipulation instead of numbers.
Fixes #688
=> Fix truncateTooLongNumber on 32 bit PHP
